#collection of static variables for referencing

#ints
PAD = 0

#strings
IGNORE='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n'    
PADDING = '***'
BRACKETS = '{[()]}'
STOPMARKS = '.!?'
SPEECHMARKS = ''''")]}>'''
NUMBERS = '0123456789 ' #purposely includes whitespace
ALPHABET = 'abcdefghijklmnopqrstuvwxyz'
VOWELS = 'aeiou'

#dictionaries
ENDINGS = { 'a': ALPHABET,      #{ultimate letters of words: possible corresponding penultimate letters}
            'b': VOWELS + 'lmr',
            'c': 'i',
            'd': VOWELS + 'rdlyn',
            'e': ALPHABET,
            'f': VOWELS + 'fl',
            'g': VOWELS + 'ngr',
            'h': 'dhcstpagek',
            'i': ALPHABET,
            'j': 'andj',
            'k': VOWELS + 'clsrny',
            'l': VOWELS + 'ylwhr',
            'm': VOWELS + 'wlmhysr',
            'n': VOWELS + 'nwrgmy',
            'o': ALPHABET,
            'p': VOWELS + 'mlspy',
            'q': 'aun',
            'r': VOWELS + 'hr',
            's': ALPHABET,
            't': VOWELS + 'cnsplrhfx',
            'u': 'saomlernykz',
            'v': VOWELS + 'r',
            'w': VOWELS,
            'x': VOWELS + 'yn',
            'y': ALPHABET,
            'z': VOWELS + 'tndslz'}
ABBREVIATIONS = {"a" : "(in dates) ante",
		"abbrev." : "abbreviation (of)",
		"abbrev." : "abbreviation(s)",
		"abd." : "Aberdeen",
		"aberd." : "Aberdeen",
		"aberdeensh." : "Aberdeenshire",
		"abl." : "ablative",
		"abol." : "abolition",
		"aborig." : "aboriginal",
		"abp." : "archbishop",
		"abr." : "abridged",
		"abridg." : "abridged",
		"abridgem." : "abridgement",
		"absol." : "absolute(ly)",
		"absol." : "absolute",
		"abst." : "abstract(s)",
		"abstr." : "abstract",
		"abstr." : "abstract(s)",
		"acad." : "academia, academy, academic(al)",
		"acc." : "according (to)",
		"acc." : "accusative",
		"acc." : "account(s)",
		"accept." : "acceptance",
		"accomm." : "accommodation",
		"accompl." : "accomplished",
		"accs." : "accounts",
		"acct." : "account",
		"accts." : "accounts",
		"accus." : "accusative",
		"achievem." : "achievement",
		"a.d." : "Anno Domini",
		"ad." : "adaptation of",
		"add." : "addendum, addenda",
		"addit." : "addition(s)",
		"addr." : "address",
		"adj." : "adjective, adjectival",
		"adj. phr." : "adjectival phrase",
		"adjs." : "adjectives",
		"adm." : "admiral",
		"adm." : "admiralty",
		"admin." : "administration, administrative",
		"admir." : "admiralty",
		"admon." : "admonition",
		"admonit." : "admonition",
		"adv." : "adverb, adverbial(ly)",
		"adv." : "advanced",
		"adv." : "advances",
		"adv." : "adventure(s)",
		"adv." : "advices",
		"adv." : "advocate",
		"advancem." : "advancement(s)",
		"advb." : "adverb, adverbial(ly)",
		"advert." : "advertisement",
		"advoc." : "advocate",
		"advs." : "adverbs",
		"advt." : "advertisement",
		"advts." : "advertisements",
		"aerodynam." : "aerodynamics",
		"aeronaut." : "aeronautics, aeronautical",
		"aff." : "affairs",
		"affect." : "affecting",
		"affect." : "affection(s)",
		"afr." : "Africa(n)",
		"agric." : "agriculture, agricultural",
		"agst." : "against",
		"alch." : "alchemy",
		"alg." : "algebra",
		"alleg." : "allegiance",
		"allit." : "alliterative",
		"alm." : "almanac",
		"alph." : "alphabet, alphabetical",
		"alt." : "alteration",
		"amer." : "America, American",
		"anal." : "analysis",
		"analyt." : "analytic(al)",
		"anat." : "anatomy, anatomical",
		"anc." : "ancient",
		"anecd." : "anecdotes",
		"ang." : "Anglian",
		"angl." : "Anglian",
		"anglo-ind." : "Anglo-Indian",
		"anim." : "animal(s)",
		"ann." : "annal(s)",
		"ann." : "annual",
		"anniv." : "anniversary",
		"annot." : "annotation",
		"anon." : "(in author names) Anonymous",
		"answ." : "answer",
		"ant." : "antiquities",
		"anthrop." : "anthropology",
		"anthropol." : "anthropology, anthropological",
		"antiq." : "antiquity, antiquities",
		"aphet." : "aphetic, aphetized",
		"apoc." : "apocalyptic(al)",
		"apol." : "apology, apologies",
		"app." : "apparently",
		"app." : "appendix",
		"appl." : "applied",
		"applic." : "application(s)",
		"appos." : "appositive(ly)",
		"apr." : "April",
		"arab." : "Arabic",
		"arb." : "(in author names) Arber",
		"arch." : "archaic",
		"arch." : "architecture",
		"arch." : "archive(s)",
		"archaeol." : "archaeology, archaeological",
		"archipel." : "archipelago",
		"archit." : "architecture, architectural",
		"argt." : "argument",
		"arith." : "arithmetic",
		"arithm." : "arithmetic, arithmetical",
		"arrangem." : "arrangement",
		"art." : "article",
		"artic." : "articulation",
		"artific." : "artificial",
		"artill." : "artillery",
		"ashm." : "(in author names) Ashmole",
		"assemb." : "assembly, assemblies",
		"assoc." : "association",
		"assoc. football" : "Association Football",
		"assyriol." : "Assyriology",
		"astr." : "astronomy",
		"astrol." : "astrology",
		"astron." : "astronomy, astronomic(al)",
		"astronaut." : "astronautics, astronautical",
		"att." : "Attic",
		"attrib." : "attributive(ly)",
		"attrib." : "attribute(s)",
		"aug." : "August",
		"austral." : "Australia(n)",
		"auth." : "author(s)",
		"autobiog." : "autobiography",
		"autobiogr." : "autobiography, autobiographic(al)",
		"a.v." : "Authorized Version",
		"ayrsh." : "Ayrshire",
		"bacteriol." : "bacteriology, bacteriologic(al)",
		"b.c." : "Before Christ",
		"b.c." : "British Columbia",
		"bedford." : "Bedfordshire",
		"bedfordsh." : "Bedfordshire",
		"bef." : "before",
		"bel & dr." : "(in the Apocrypha) Bel and the Dragon",
		"belg." : "Belgian",
		"berks." : "Berkshire",
		"berksh." : "Berkshire",
		"berw." : "Berwickshire",
		"berwicksh." : "Berwickshire",
		"betw." : "between",
		"bibliogr." : "bibliography",
		"biochem." : "biochemistry, biochemical",
		"biog." : "biography",
		"biogr." : "biography, biographic(al)",
		"biol." : "biology, biological",
		"bk." : "book",
		"bks." : "books",
		"bnc" : "British National Corpus",
		"bord." : "border",
		"bot." : "botany, botanic(al)",
		"bp." : "Bishop",
		"braz." : "Brazilian",
		"brit." : "Britain, British",
		"bucks." : "Buckinghamshire",
		"build." : "building",
		"bull." : "bulletin",
		"bur." : "bureau",
		"c." : "century",
		"c." : "county, counties",
		"c" : "(in dates) circa",
		"cal." : "calendar",
		"calc." : "calculus",
		"calend." : "calendar",
		"calif." : "California",
		"calligr." : "calligraphy",
		"camb." : "Cambridge",
		"cambr." : "Cambridge",
		"campanol." : "campanology",
		"canad." : "Canadian",
		"canterb." : "Canterbury",
		"capt." : "captain",
		"cartogr." : "cartography, cartographic(al)",
		"catal." : "catalogue",
		"catech." : "catechism",
		"cath." : "Catholic",
		"cent." : "century",
		"cent." : "central",
		"cent." : "century",
		"ceram." : "ceramics",
		"cert." : "certificate",
		"certif." : "certificate",
		"cf." : "confer, �compare�",
		"ch." : "Church",
		"chamb." : "chamber",
		"char." : "character",
		"charac." : "character",
		"chas." : "Charles",
		"chem. engin." : "chemical engineering",
		"chem." : "chemistry, chemical",
		"chesh." : "Cheshire",
		"ch. hist." : "Church history",
		"chr." : "Christian",
		"chr." : "(in the Bible) Chronicles",
		"chron." : "chronology, chronicle",
		"chron." : "(in the Bible) Chronicles",
		"chronol." : "chronology",
		"chrons." : "chronicles",
		"cinematogr." : "cinematography, cinematographic(al)",
		"circ." : "circle",
		"civ. law" : "civil law",
		"civil engin." : "civil engineering",
		"cl." : "clause",
		"cl." : "club",
		"class. antiq." : "classical antiquities",
		"class." : "classical",
		"classif." : "classification",
		"climatol." : "climatology",
		"clin." : "clinical",
		"cogn. w." : "cognate with",
		"col." : "colonel",
		"col." : "(in the Bible) Colossians",
		"coll." : "collected, collection",
		"coll." : "college",
		"collect." : "collective(ly)",
		"collect." : "collection",
		"colloq." : "colloquial(ly)",
		"colloq." : "colloquies",
		"coloss." : "(in the Bible) Colossians",
		"com." : "common",
		"com." : "commission",
		"comb." : "combination(s)",
		"comb. form" : "combining form",
		"combs." : "combinations",
		"comm." : "commerce, in commercial usage",
		"comm." : "common",
		"comm." : "commentary",
		"comm." : "commission",
		"comm." : "committee",
		"commandm." : "commandment",
		"commend." : "commendation",
		"commerc." : "commercial",
		"commiss." : "commission",
		"comm. law" : "commercial law",
		"commonw." : "commonwealth",
		"communic." : "communication(s)",
		"comp." : "comparative",
		"comp." : "compound, composition",
		"comp." : "companion",
		"comp." : "company",
		"compan." : "companion(s)",
		"comp. anat." : "comparative anatomy",
		"compar." : "comparative",
		"compar." : "comparative",
		"compend." : "compendium, compendious",
		"compl." : "complement",
		"compl." : "complete",
		"compos." : "composition",
		"conc." : "concerning",
		"conc." : "concise",
		"conch." : "conchology",
		"concl." : "conclusion",
		"concr." : "concrete(ly)",
		"conf." : "conference",
		"conf." : "confession",
		"confid." : "confidential",
		"confl." : "conflict",
		"confut." : "confutation",
		"congr." : "congress",
		"congreg." : "congregation",
		"congress." : "congressional",
		"conj." : "conjugation",
		"conj." : "conjunction",
		"conn." : "Connecticut",
		"cons." : "consonant",
		"consc." : "conscience",
		"consecr." : "consecrated, consecration",
		"consid." : "consideration(s)",
		"consol." : "consolation",
		"const." : "construction, construed with",
		"constit. hist." : "constitutional history",
		"constit." : "constitution(al)",
		"constr." : "construction",
		"contemp." : "contemporary",
		"contempl." : "contemplation",
		"contempt." : "contemptuous(ly)",
		"contend." : "contending(s)",
		"content." : "contention",
		"contin." : "continuation",
		"contr." : "contracted, contraction",
		"contr." : "contrasted (with)",
		"contradict." : "contradiction",
		"contrib." : "contribution",
		"controv." : "controversial",
		"controv." : "controversy",
		"conv." : "convention",
		"convent." : "convention",
		"conversat." : "conversation",
		"convoc." : "convocation",
		"cor." : "(in the Bible) Corinthians",
		"cornw." : "Cornwall",
		"coron." : "coronation",
		"corr." : "correspondence",
		"corresp." : "corresponding (to)",
		"corresp." : "correspondence",
		"counc." : "council",
		"courtsh." : "courtship",
		"cpd." : "compound",
		"craniol." : "craniology",
		"craniom." : "craniometry",
		"crim." : "criminal",
		"crim. law" : "criminal law",
		"crit." : "critical",
		"crit." : "criticism",
		"crt." : "court",
		"crts." : "courts",
		"cryptogr." : "cryptography",
		"crystallogr." : "crystallography",
		"ct." : "count",
		"ct." : "court",
		"cumb." : "Cumberland",
		"cumberld." : "Cumberland",
		"cumbld." : "Cumberland",
		"cycl." : "cyclopaedia",
		"cytol." : "cytology, cytological",
		"dan." : "(in the Bible) Daniel",
		"dat." : "dative",
		"dau." : "daughter",
		"d.c." : "District of Columbia",
		"deb." : "debate",
		"dec." : "December",
		"declar." : "declaration",
		"ded." : "dedicated",
		"ded." : "dedication",
		"def." : "definite",
		"def." : "definition",
		"def." : "defence",
		"deliv." : "deliverance",
		"dem." : "demonstrative",
		"demonstr." : "demonstration",
		"dep." : "department",
		"dep." : "deputy",
		"depred." : "depredation",
		"depredat." : "depredation",
		"dept." : "department",
		"derbysh." : "Derbyshire",
		"deriv." : "derivative (in etymologies)",
		"derog." : "derogatory",
		"descr." : "description, descriptive",
		"deut." : "(in the Bible) Deuteronomy",
		"devel." : "development",
		"devonsh." : "Devonshire",
		"dial." : "dialect",
		"dial." : "dialect",
		"dict." : "dictionary",
		"diffic." : "difficult, difficulty",
		"dim." : "diminutive",
		"direct." : "direction",
		"dis." : "disease(s)",
		"disc." : "discourse",
		"discipl." : "discipline",
		"discov." : "discovery",
		"discrim." : "discrimination",
		"discuss." : "discussion",
		"diss." : "dissertation",
		"dist." : "district",
		"distemp." : "distemper",
		"distill." : "distilling",
		"distrib." : "distribution",
		"div." : "divinity",
		"div." : "division",
		"divers." : "diversity",
		"dk." : "Duke",
		"doc." : "document(s)",
		"doctr." : "doctrine",
		"domest." : "domestic",
		"durh." : "Durham",
		"dyslog." : "dyslogistic",
		"e." : "east",
		"e." : "east, eastern",
		"e. afr." : "East Africa(n)",
		"e. angl." : "East Anglia(n)",
		"e. anglian" : "East Anglian",
		"east ind." : "East Indies, East Indian",
		"east." : "eastern (dialect)",
		"eccl." : "ecclesiastical",
		"eccl." : "(in the Bible) Ecclesiastes",
		"eccles." : "ecclesiastical",
		"eccles." : "(in the Bible) Ecclesiastes",
		"eccl. hist." : "ecclesiastical history",
		"eccl. law" : "ecclesiastical law",
		"ecclus." : "(in the Apocrypha) Ecclesiasticus",
		"ecol." : "ecology, ecological",
		"econ." : "economics, economic(al)",
		"ed." : "edition",
		"ed." : "edition",
		"ed." : "Edward",
		"e.d.d." : "English Dialect Dictionary",
		"edin." : "Edinburgh",
		"edinb." : "Edinburgh",
		"educ." : "education, education(al)",
		"edw." : "Edward",
		"e.e.t.s." : "Early English Text Society",
		"egypt." : "Egyptian",
		"egyptol." : "Egyptology",
		"e. ind." : "East Indies, East Indian",
		"electr." : "electricity, electric(al)",
		"electr. engin." : "electrical engineering",
		"electro-magn." : "electro-magnetism",
		"electro-physiol." : "electro-physiology",
		"elem." : "element(s), elementary",
		"eliz." : "Elizabeth",
		"elizab." : "Elizabethan",
		"ellipt." : "elliptical(ly)",
		"emb." : "embassy",
		"embryol." : "embryology, embryologic(al)",
		"e. midl." : "east midland (dialect)",
		"emph." : "emphatic(ally)",
		"encycl." : "encyclopaedia, encyclopaedic",
		"encycl. brit." : "Encyclopaedia Britannica",
		"encycl. metrop." : "Encyclopaedia Metropolitana",
		"eng." : "England, English",
		"engin." : "engineering",
		"englishw." : "Englishwomen",
		"enq." : "enquiry",
		"ent." : "entomology, entomological",
		"enthus." : "enthusiasm",
		"entom." : "entomology, entomological",
		"entomol." : "entomology, entomological",
		"enzymol." : "enzymology",
		"eoe" : "(in dates) early Old English",
		"ep." : "epistle",
		"eph." : "(in the Bible) Ephesians",
		"ephes." : "(in the Bible) Ephesians",
		"epil." : "epilogue",
		"episc." : "episcopacy",
		"epist." : "epistle",
		"epit." : "epitaph",
		"equip." : "equipment",
		"erron." : "erroneous(ly)",
		"esd." : "(in the Apocrypha) Esdras",
		"esp." : "especially",
		"ess." : "essay(s)",
		"essent." : "essential",
		"establ." : "establishment",
		"esth." : "(in the Bible) Esther",
		"ethnol." : "ethnology",
		"etym." : "etymology",
		"etymol." : "etymological(ly)",
		"etymol." : "etymology, etymological",
		"euphem." : "euphemistic(ally)",
		"eval." : "evaluation",
		"evang." : "evangelical",
		"even." : "evening",
		"evid." : "evidence",
		"evol." : "evolution, evolutionary",
		"ex. doc." : "executive document",
		"exalt." : "exaltation",
		"exam." : "examination",
		"exc." : "except",
		"exch." : "exchange",
		"exch." : "exchequer",
		"exec." : "execution",
		"exec." : "executive",
		"exerc." : "exercise(s)",
		"exhib." : "exhibition, exhibit(s)",
		"exod." : "(in the Bible) Exodus",
		"exped." : "expedition",
		"exper." : "experiment, experimental",
		"explan." : "explanation",
		"explic." : "explication",
		"explor." : "exploration",
		"expos." : "exposition, expository",
		"ezek." : "(in the Bible) Ezekiel",
		"f." : "feminine",
		"f." : "folio",
		"fab." : "fable(s)",
		"fam." : "familiar(ly)",
		"fam." : "family",
		"famil." : "familiar(ly)",
		"farew." : "farewell",
		"feb." : "February",
		"fem." : "feminine",
		"ff." : "folios",
		"fifesh." : "Fifeshire",
		"fig." : "figurative(ly)",
		"fl." : "floruit, �flourished�",
		"footpr." : "footprint",
		"forfarsh." : "Forfarshire",
		"fortif." : "fortification",
		"fortn." : "fortnightly",
		"found." : "foundation(s)",
		"fr." : "father",
		"fr." : "French",
		"fr." : "from",
		"fragm." : "fragment(s)",
		"fratern." : "fraternity",
		"freq." : "frequently",
		"friendsh." : "friendship",
		"fund." : "fundamental(s)",
		"furnit." : "furniture",
		"fut." : "future",
		"gal." : "(in the Bible) Galatians",
		"gard." : "garden, gardening",
		"gastron." : "gastronomy",
		"gaz." : "gazette",
		"gd." : "good",
		"gen." : "general(ly)",
		"gen." : "genitive",
		"gen." : "general",
		"gen." : "(in the Bible) Genesis",
		"geo." : "George",
		"geog." : "geography",
		"geogr." : "geography, geographic(al)",
		"geol." : "geology, geologic(al)",
		"geom." : "geometry, geometric(al)",
		"geomorphol." : "geomorphology",
		"ger." : "German",
		"gerund." : "gerundial",
		"glac." : "glacier(s)",
		"glasg." : "Glasgow",
		"glos." : "Gloucestershire",
		"gloss." : "glossary",
		"glouc." : "Gloucestershire",
		"gloucestersh." : "Gloucestershire",
		"gosp." : "gospel(s)",
		"gov." : "government",
		"govt." : "government",
		"gr." : "grammar",
		"gram." : "grammar",
		"gramm. analysis" : "grammatical analysis",
		"gt." : "great",
		"gynaecol." : "gynaecology",
		"hab." : "(in the Bible) Habakkuk",
		"haematol." : "haematology",
		"hag." : "(in the Bible) Haggai",
		"hampsh." : "Hampshire",
		"handbk." : "handbook",
		"hants." : "Hampshire",
		"heb." : "Hebrew",
		"heb." : "(in the Bible) Hebrews",
		"hebr." : "(in the Bible) Hebrews",
		"hen." : "Henry",
		"her." : "heraldry",
		"herb." : "herbalism",
		"heref." : "Herefordshire",
		"hereford." : "Herefordshire",
		"herefordsh." : "Herefordshire",
		"hertfordsh." : "Hertfordshire",
		"hierogl." : "Hieroglyphic",
		"hist." : "historical",
		"hist." : "history, historic(al)",
		"histol." : "histology, histologic(al)",
		"hom." : "homilies",
		"horol." : "horology",
		"hort." : "horticulture, horticultural",
		"hos." : "(in the Bible) Hosea",
		"hosp." : "hospital",
		"househ." : "household",
		"housek." : "housekeeping",
		"husb." : "husbandry",
		"hydraul." : "hydraulic",
		"hydrol." : "hydrology, hydrological",
		"ichth." : "ichthyology",
		"icthyol." : "icthyology",
		"ideol." : "ideology, ideological",
		"idol." : "idolatry",
		"illustr." : "illustrated, illustration(s)",
		"imag." : "imaginary, imagination",
		"imit." : "imitative",
		"immunol." : "immunology",
		"imp." : "imperative",
		"imperf." : "imperfect",
		"impers." : "impersonal",
		"impf." : "imperfect",
		"impr." : "impression(s)",
		"impr." : "imprint",
		"impr." : "improved",
		"improp." : "improper(ly)",
		"inaug." : "inaugural",
		"inclos." : "inclosure",
		"ind." : "India(n)",
		"ind." : "indicative",
		"ind." : "indirect",
		"ind." : "industry",
		"indef." : "indefinite",
		"indic." : "indicative",
		"indir." : "indirect",
		"industr." : "industrial",
		"industr. rel." : "industrial relations",
		"infin." : "infinitive",
		"infl." : "influenced",
		"infl." : "influence",
		"innoc." : "innocence, innocent",
		"inorg." : "inorganic",
		"inq." : "inquiry",
		"inst." : "institute, institution",
		"instr." : "instrumental",
		"instr." : "instruction",
		"int." : "interjection",
		"intell." : "intelligence, intelligent",
		"intellect." : "intellectual",
		"interc." : "intercourse",
		"interj." : "interjection",
		"interl." : "interlude",
		"internat." : "international",
		"interpr." : "interpretation",
		"interrog." : "interrogative",
		"intr." : "intransitive",
		"intrans." : "intransitive",
		"intro." : "introduction",
		"introd." : "introduction, introductory",
		"inv." : "inventory, inventories",
		"invent." : "invention(s)",
		"invent." : "inventory, inventories",
		"invertebr." : "invertebrate, invertebrated",
		"invert. zool." : "invertebrate zoology",
		"investig." : "investigation",
		"investm." : "investment",
		"invoc." : "invocation",
		"ir." : "Irish",
		"irel." : "Ireland",
		"iron." : "ironically",
		"irreg." : "irregular(ly)",
		"isa." : "(in the Bible) Isaiah",
		"ital." : "Italian",
		"jahrb." : "Jahrbuch",
		"jam." : "(in the Bible) James",
		"jam." : "(in author names) Jamieson",
		"jan." : "January",
		"jap." : "Japanese",
		"jas." : "James",
		"jas." : "(in the Bible) James",
		"jer." : "(in the Bible) Jeremiah",
		"joc." : "jocular(ly)",
		"josh." : "(in the Bible) Joshua",
		"jrnl." : "journal",
		"jrnls." : "journals",
		"jud." : "(in the Bible) Judges",
		"judg." : "(in the Bible) Judges",
		"jul." : "July",
		"jun." : "June",
		"jun." : "junior",
		"jurisd." : "jurisdiction",
		"jurisdict." : "jurisdiction",
		"jurispr." : "jurisprudence",
		"justif." : "justification",
		"justific." : "justification",
		"k." : "king",
		"kent." : "Kentish",
		"kgs." : "(in the Bible) Kings",
		"king�s bench div." : "King�s Bench Division",
		"kingd." : "kingdom",
		"knowl." : "knowledge",
		"kpr." : "keeper",
		"l." : "line",
		"lab." : "laboratory",
		"lam." : "(in the Bible) Lamentations",
		"lament" : "lamentation",
		"lament." : "(in the Bible) Lamentations",
		"lanc." : "Lancashire",
		"lancash." : "Lancashire",
		"lancs." : "Lancashire",
		"lang." : "language",
		"langs." : "languages",
		"lat." : "Latin",
		"ld." : "Lord",
		"lds." : "Lords",
		"lect." : "lecture(s)",
		"leechd." : "leechdom",
		"leg." : "legend(s)",
		"leicest." : "Leicestershire",
		"leicester." : "Leicestershire",
		"leicestersh." : "Leicestershire",
		"leics." : "Leicestershire",
		"let." : "letter",
		"lett." : "letters",
		"lev." : "(in the Bible) Leviticus",
		"lex." : "lexicon",
		"libr." : "library",
		"limnol." : "limnology",
		"lincolnsh." : "Lincolnshire",
		"lincs." : "Lincolnshire",
		"ling." : "linguistic(s)",
		"linn." : "Linnean",
		"lit." : "literal(ly)",
		"lit." : "literary, literature",
		"lithogr." : "lithography",
		"lithol." : "lithology",
		"liturg." : "liturgy",
		"ll." : "lines",
		"loe" : "(in dates) late Old English",
		"lond." : "London",
		"lxx" : "Septuagint",
		"m." : "masculine",
		"macc." : "(in the Apocrypha) Maccabees",
		"mach." : "machinery, machine(s)",
		"mag." : "magazine",
		"magn." : "magnetism, magnetic",
		"mal." : "(in the Bible) Malachi",
		"man." : "manual",
		"managem." : "management",
		"manch." : "Manchester",
		"manip." : "manipulation",
		"manuf." : "manufacturing, manufacture(s)",
		"mar." : "March",
		"masc." : "masculine",
		"mass." : "Massachussets",
		"math." : "mathematics, mathematical",
		"matt." : "(in the Bible) Matthew",
		"meas." : "measure",
		"measurem." : "measurement",
		"mech." : "mechanics, mechanical",
		"med." : "medieval",
		"med." : "medicine, medical",
		"medit." : "meditation",
		"mem." : "memoir(s)",
		"merc." : "mercury",
		"merch." : "merchant(s)",
		"metall." : "metallurgy",
		"metallif." : "metalliferous",
		"metallogr." : "metallography, metallographic(al)",
		"metallogr." : "metallography",
		"metamorph." : "metamorphosis",
		"metaph." : "metaphysics",
		"metaphor." : "metaphorical(ly)",
		"meteorol." : "meteorology, meteorologic(al)",
		"meth." : "method(s)",
		"metr. gr." : "metri gratia",
		"metrop." : "metropolitan, metropolis",
		"mex." : "Mexican",
		"mic." : "(in the Bible) Micah",
		"mich." : "Michigan",
		"microbiol." : "microbiology",
		"microsc." : "microscopic(al)",
		"midl." : "midland(s) (dialect)",
		"mil." : "military",
		"milit." : "military",
		"min." : "mineralogy",
		"mineral." : "mineralogy, minaralogic(al)",
		"misc." : "miscellaneous, miscellany",
		"miscell." : "miscellany",
		"mispr." : "misprinted",
		"mod." : "modern",
		"mod." : "modern",
		"monum." : "monument",
		"morphol." : "morphology",
		"ms." : "manuscript",
		"mss." : "manuscripts",
		"mt." : "mount(ain)",
		"mtg." : "meeting",
		"mts." : "mountains",
		"munic." : "municipal",
		"munif." : "munificence",
		"munim." : "muniment",
		"mus." : "music, musical",
		"mus." : "museum",
		"myst." : "mystery",
		"myth." : "mythology",
		"mythol." : "mythology",
		"n." : "neuter",
		"n." : "north",
		"n." : "noun",
		"n." : "north, northern",
		"n. afr." : "North Africa(n)",
		"nah." : "(in the Bible) Nahum",
		"n. amer." : "North America(n)",
		"narr." : "narrative",
		"narrat." : "narrative",
		"nat." : "natural",
		"nat. hist." : "natural history",
		"nat. philos." : "natural philosophy",
		"nat. sci." : "natural science",
		"naut." : "nautical",
		"nav." : "naval",
		"nav." : "navigation",
		"navig." : "navigation",
		"n. carolina" : "North Carolina",
		"n. dakota" : "North Dakota",
		"n.e." : "north-eastern (dialect)",
		"n.e." : "north-east, north-eastern",
		"n.e.d." : "New English Dictionary",
		"neh." : "(in the Bible) Nehemiah",
		"neighb." : "neighbour(s), neighbourhood",
		"nerv." : "nervous",
		"neurol." : "neurology, neurologic(al)",
		"neurosurg." : "neurosurgery",
		"new hampsh." : "New Hampshire",
		"newc." : "Newcastle",
		"newspr." : "newsprint",
		"n. ir." : "Northern Irish",
		"n. irel." : "Northern Ireland",
		"no." : "number",
		"nom." : "nominative",
		"non-conf." : "nonconformist(s)",
		"nonce-wd." : "nonce-word",
		"nonconf." : "nonconformist(s)",
		"norf." : "Norfolk",
		"north." : "northern (dialect)",
		"northamptonsh." : "Northamptonshire",
		"northants." : "Northamptonshire",
		"northumb." : "Northumberland, Northumbrian",
		"northumbld." : "Northumberland",
		"northumbr." : "Northumbrian",
		"norw." : "Norwegian",
		"norweg." : "Norwegian",
		"notts." : "Nottinghamshire",
		"nov." : "November",
		"ns." : "nouns",
		"n.s. wales" : "New South Wales",
		"n.s.w." : "New South Wales",
		"n.t." : "New Testament",
		"nucl." : "nuclear",
		"num." : "(in the Bible) Numbers",
		"numism." : "numismatics",
		"n.w." : "north-western (dialect)",
		"n.w." : "north-west, north-western",
		"n.y." : "New York",
		"n.z." : "New Zealand",
		"obad." : "(in the Bible) Obadiah",
		"obed." : "obedience",
		"obj." : "object, objective",
		"obj." : "object(s)",
		"obl." : "oblique",
		"obs." : "obsolete",
		"obs." : "obsolete",
		"observ." : "observation(s)",
		"obstet." : "obstetric(s)",
		"obstetr." : "obstetric(s)",
		"obstetr. med." : "obstetric medicine",
		"occas." : "occasionally",
		"occas." : "occasional",
		"occup." : "occupation(al)",
		"occurr." : "occurrence",
		"oceanogr." : "oceanography, oceanographic(al)",
		"oct." : "October",
		"oe" : "(in dates) Old English",
		"o.e.d." : "Oxford English Dictionary",
		"off." : "official, office",
		"offic." : "official",
		"okla." : "Oklahoma",
		"ont." : "Ontario",
		"ophthalm." : "ophthalmology",
		"ophthalmol." : "ophthalmology, ophtalmologic(al)",
		"opp." : "opposed (to), the opposite (of)",
		"oppress." : "oppression",
		"opt." : "optics",
		"orac." : "oracle(s)",
		"ord." : "order(s)",
		"ord." : "ordinance(s)",
		"org." : "organic",
		"organ. chem." : "organic chemistry",
		"org. chem." : "organic chemistry",
		"orig." : "origin(al)(ly)",
		"orig." : "original",
		"orkn." : "Orkney",
		"ornith." : "ornithology",
		"ornithol." : "ornithology, ornithologic(al)",
		"orthogr." : "orthography",
		"o.t." : "Old Testament",
		"outl." : "outline",
		"oxf." : "Oxford",
		"oxfordsh." : "Oxfordshire",
		"oxon." : "Oxfordshire",
		"p." : "page",
		"pa." : "past",
		"pa." : "Pennsylvania",
		"palaeobot." : "palaeobotany",
		"palaeogr." : "palaeography",
		"palaeont." : "palaeontology",
		"palaeontol." : "palaeontology, palaeontologic(al)",
		"pa. pple." : "passive participle, past participle",
		"paraphr." : "paraphrase, paraphrased",
		"parasitol." : "parasitology",
		"parl." : "parliament, parliamentary",
		"parnass." : "Parnassus",
		"pass." : "passive(ly)",
		"pa. t." : "past tense",
		"path." : "pathology, pathologic(al)",
		"pathol." : "pathology, pathologic(al)",
		"peculat." : "peculation(s)",
		"penins." : "peninsula",
		"perf." : "perfect",
		"perf." : "perfect, perfection",
		"perh." : "perhaps",
		"periodontol." : "periodontology, periodontologic(al)",
		"pers." : "person(al)",
		"pers." : "Persian",
		"pers." : "personal",
		"persec." : "persecution(s)",
		"personif." : "personified",
		"perthsh." : "Perthshire",
		"pet." : "(in the Bible) Peter",
		"petrogr." : "petrography, petrographic(al)",
		"petrol." : "petrology, petrologic(al)",
		"pf." : "perfect",
		"pharm." : "pharmacology",
		"pharmaceut." : "pharmaceutical",
		"pharmacol." : "pharmacology, pharmacological",
		"phil." : "philosophy, philosophic(al)",
		"phil." : "(in the Bible) Philippians",
		"philad." : "Philadelphia",
		"philem." : "(in the Bible) Philemon",
		"philipp." : "(in the Bible) Philippians",
		"philol." : "philology, philologic(al)",
		"philos." : "philosophy, philosophic(al)",
		"phoen." : "Phoenician",
		"phonet." : "phonetic(ally)",
		"phonol." : "phonology",
		"photog." : "photography",
		"photogr." : "photography, photographic(al)",
		"phr." : "phrase",
		"phrenol." : "phrenology",
		"phys." : "physiology",
		"physical chem." : "physical chemistry",
		"physical geogr." : "physical geography",
		"physiogr." : "physiography",
		"physiol." : "physiology, physiologic(al)",
		"pict." : "pictorial",
		"pict." : "picture(s)",
		"pl." : "plural",
		"plur." : "plural",
		"poet." : "poetic(al)",
		"poet." : "poetical",
		"pol." : "politics, political",
		"pol. econ." : "political economy",
		"polit." : "politics, political",
		"polytechn." : "polytechnic(al)",
		"pop." : "popular(ly)",
		"pop." : "popular",
		"porc." : "porcelain",
		"port." : "Portuguese",
		"poss." : "possessive",
		"poss." : "possible, possibly",
		"posth." : "posthumous(ly)",
		"postm." : "postmaster",
		"pott." : "pottery",
		"ppl." : "participial",
		"ppl. a." : "participial adjective",
		"ppl. adj." : "participial adjective",
		"ppl. adjs." : "participial adjectives",
		"pple." : "participle",
		"pples." : "participles",
		"p. r." : "public records",
		"pr." : "present",
		"pract." : "practical",
		"pract." : "practice",
		"prec." : "preceding",
		"pred." : "predicate",
		"predic." : "predicate, predicative(ly)",
		"predict." : "prediction",
		"pref." : "prefix",
		"pref." : "preface",
		"preh." : "prehistoric",
		"prehist." : "prehistory, prehistoric",
		"prep." : "preposition(al)",
		"prerog." : "prerogative",
		"pres." : "present",
		"pres." : "present",
		"presb." : "Presbyterian",
		"presb." : "presbytery",
		"preserv." : "preservation",
		"pres. pple." : "present participle",
		"prim." : "primer(s)",
		"princ." : "principle(s)",
		"print." : "printing",
		"priv." : "privative",
		"prob." : "probably",
		"probab." : "probability, probabilities",
		"probl." : "problem",
		"proc." : "proceedings",
		"prod." : "product(s)",
		"prol." : "prologue",
		"pron." : "pronoun",
		"pron." : "pronunciation",
		"pronunc." : "pronunciation",
		"pronunc." : "pronunciation",
		"prop." : "properly",
		"prop." : "property, properties",
		"propr." : "proprietary",
		"pros." : "prosody",
		"prov." : "proverb(ial)(ly)",
		"prov." : "proverb",
		"prov." : "(in the Bible) Proverbs",
		"provid." : "providence(s)",
		"provinc." : "provincial",
		"provis." : "provisional",
		"pr. pple." : "present participle",
		"ps." : "(in the Bible) Psalms",
		"pseudo-arch." : "pseudo-archaic",
		"pseudo-dial." : "pseudo-dialect",
		"pseudo-sc." : "pseudo-Scots",
		"psych." : "psychology",
		"psychoanal." : "psychoanalysis",
		"psychoanalyt." : "psychoanalytic",
		"psychol." : "psychology, psychologic(al)",
		"psychopathol." : "psychopathology, psychopathologic(al)",
		"pt." : "part",
		"publ." : "public",
		"publ." : "publication",
		"purg." : "purgatory",
		"q." : "quarterly",
		"q." : "queen",
		"q. eliz." : "Queen Elizabeth",
		"qld." : "Queensland",
		"quantum mech." : "quantum mechanics",
		"queen�s bench div." : "Queen�s Bench Division",
		"quot." : "quotation",
		"quots." : "quotations",
		"q.v." : "quod vide, �which see�",
		"r." : "royal",
		"radiol." : "radiology",
		"r.a.f." : "Royal Air Force",
		"r.c." : "Roman Catholic(ism)",
		"r.c. church" : "Roman Catholic Church",
		"reas." : "reason(s)",
		"reb." : "rebellion",
		"rebell." : "rebellion",
		"rec." : "record(s)",
		"reclam." : "reclamation",
		"recoll." : "recollection",
		"redempt." : "redemption",
		"redupl." : "reduplicating",
		"ref." : "reference",
		"ref." : "reformation",
		"refash." : "refashioned, refashioning",
		"refl." : "reflexive",
		"refl." : "reflection(s)",
		"refus." : "refusal",
		"refut." : "refutation",
		"reg." : "regular",
		"reg." : "register",
		"regic." : "regicide",
		"regist." : "register",
		"regr." : "register",
		"rel." : "related",
		"rel." : "relative",
		"rel." : "relating",
		"relig." : "religion, religious",
		"reminisc." : "reminiscence(s)",
		"remonstr." : "remonstrance",
		"renfrewsh." : "Renfrewshire",
		"rep." : "report",
		"repr." : "representative, representing",
		"reprod." : "reproduction, reproductive",
		"rept." : "report",
		"repub." : "republic",
		"res." : "research",
		"resid." : "residence, residential",
		"ret." : "return",
		"retrosp." : "retrospective",
		"rev." : "review",
		"rev." : "revised",
		"rev." : "(in the Bible) Revelation",
		"revol." : "revolution",
		"rhet." : "rhetoric",
		"rhet." : "rhetorical(ly)",
		"rhode isl." : "Rhode Island",
		"rich." : "Richard",
		"r.n." : "Royal Navy",
		"rom." : "Roman",
		"rom." : "(in the Bible) Romans",
		"rom. antiq." : "Roman antiquities",
		"ross-sh." : "Ross-shire",
		"roxb." : "Roxburgh",
		"roy." : "royal",
		"rudim." : "rudiment(s)",
		"russ." : "Russia, Russian",
		"s." : "south",
		"s." : "south, southern",
		"s. afr." : "South Africa(n)",
		"sam." : "(in the Bible) Samuel",
		"sask." : "Saskatchewan",
		"sat." : "Saturday",
		"sax." : "Saxon",
		"sc." : "scilicet, �understand� or �supply�",
		"sc." : "Scottish, Scots",
		"scand." : "Scandinavia, Scandinavian",
		"s. carolina" : "South Carolina",
		"sch." : "school",
		"sci." : "science(s), scientific",
		"scot." : "Scottish",
		"scotl." : "Scotland",
		"script." : "scripture",
		"sculpt." : "sculpture",
		"s. dakota" : "South Dakota",
		"s.e." : "south-eastern (dialect)",
		"s.e." : "south-east, south-eastern",
		"seismol." : "seismology",
		"sel." : "selected",
		"sel. comm." : "select committee",
		"select." : "selection",
		"sept." : "September",
		"ser." : "series",
		"serm." : "sermon(s)",
		"sess." : "session",
		"settlem." : "settlement",
		"sev." : "several",
		"shakes." : "Shakespeare",
		"shaks." : "Shakespeare",
		"sheph." : "shepherd",
		"shetl." : "Shetland",
		"shropsh." : "Shropshire",
		"sing." : "singular",
		"soc." : "society",
		"sociol." : "sociology, sociological",
		"som." : "Somerset",
		"song of sol." : "(in the Bible) Song of Solomon",
		"song sol." : "(in the Bible) Song of Solomon",
		"sonn." : "sonnet",
		"south." : "southern (dialect)",
		"sp." : "spelling",
		"span." : "Spanish",
		"spec." : "specifically",
		"spec." : "special",
		"spec." : "specimen(s)",
		"specif." : "specification(s)",
		"specim." : "specimen(s)",
		"spectrosc." : "spectroscopy",
		"ss." : "saints",
		"st." : "Saint",
		"st." : "street",
		"staff." : "Staffordshire",
		"stafford." : "Staffordshire",
		"staffordsh." : "Staffordshire",
		"staffs." : "Staffordshire",
		"stand." : "standard",
		"stat." : "statistical",
		"statist." : "statistical",
		"stock exch." : "stock exchange",
		"str." : "strong",
		"stratigr." : "stratigraphy, stratigraphical",
		"struct." : "structure, structural",
		"s.t.s." : "Scottish Text Society",
		"stud." : "studies",
		"subj." : "subject",
		"subj." : "subjunctive",
		"subj." : "subject(s)",
		"subjunct." : "subjunctive",
		"subord." : "subordinate",
		"subord. cl." : "subordinate clause",
		"subscr." : "subscription",
		"subscript." : "subscription",
		"subseq." : "subsequent(ly)",
		"subst." : "substantive(ly)",
		"suff." : "suffix",
		"suff." : "Suffolk",
		"superl." : "superlative",
		"suppl." : "supplement, supplementary",
		"supplic." : "supplication(s)",
		"suppress." : "suppression",
		"surg." : "surgery, surgical",
		"surv." : "survey, surveying",
		"sus." : "(in the Apocrypha) Susanna",
		"s.v." : "sub verbo, �under the word�",
		"s.w." : "south-western (dialect)",
		"s.w." : "south-west, south-western",
		"syll." : "syllable",
		"symmetr." : "symmetrical",
		"symp." : "symposium",
		"syst." : "system",
		"t." : "tense",
		"taxon." : "taxonomy, taxonomic",
		"techn." : "technical",
		"techn." : "technical",
		"technol." : "technology, technological",
		"tel." : "telegraph",
		"telecomm." : "telecommunications",
		"telegr." : "telegraph",
		"telegr." : "telegraphy, telegraphic(al)",
		"teleph." : "telephony, telephonic",
		"teratol." : "teratology",
		"terminol." : "terminology, terminological",
		"terrestr." : "terrestrial",
		"test." : "testament",
		"textbk." : "textbook",
		"theat." : "theatre, theatrical",
		"theatr." : "theatre, theatrical",
		"theol." : "theology, theological",
		"theoret." : "theoretical",
		"thermonucl." : "thermonuclear",
		"thes." : "thesaurus",
		"thess." : "(in the Bible) Thessalonians",
		"tim." : "(in the Bible) Timothy",
		"tit." : "(in the Bible) Titus",
		"topogr." : "topography, topographic(al)",
		"tr." : "translation, translating",
		"trad." : "tradition, traditional",
		"trag." : "tragedy",
		"trans." : "transitive",
		"trans." : "transaction(s)",
		"transf." : "transferred sense",
		"transl." : "translation, translating",
		"transl." : "translation",
		"transubstant." : "transubstantiation",
		"trav." : "travel(s)",
		"treas." : "treasurer, treasury",
		"treat." : "treatise",
		"treatm." : "treatment",
		"trib." : "tribune",
		"trig." : "trigonometry",
		"trigonom." : "trigonometry",
		"trop." : "tropical",
		"troub." : "troublesome",
		"troubl." : "troublesome",
		"typog." : "typography",
		"typogr." : "typography",
		"u.k." : "United Kingdom",
		"ult." : "ultimately",
		"univ." : "university",
		"unkn." : "unknown",
		"unnat." : "unnatural",
		"unoffic." : "unofficial",
		"unstr." : "unstressed",
		"urin." : "urinary",
		"u.s." : "United States",
		"u.s.a.f." : "United States Air Force",
		"u.s.s.r." : "Union of Soviet Socialist Republics",
		"usu." : "usually",
		"utilit." : "utilitarian",
		"v." : "verb",
		"va." : "Virginia",
		"vac." : "vacation",
		"valedict." : "valediction",
		"var." : "variant",
		"varr." : "variants",
		"vars." : "variants",
		"vb." : "verb",
		"vbl." : "verbal",
		"vbl.n." : "verbal noun",
		"vbl. ns." : "verbal nouns",
		"vbs." : "verbs",
		"veg." : "vegetable",
		"veg. phys." : "vegetable physiology",
		"veg. physiol." : "vegetable physiology",
		"venet." : "Venetian",
		"vertebr." : "vertebrate",
		"vet." : "veterinary, veterinary science",
		"vet. med." : "veterinary medicine",
		"vet. path." : "veterinary pathology",
		"vet. sci." : "veterinary science",
		"vet. surg." : "veterinary surgery",
		"vic." : "Victoria",
		"vict." : "Victoria",
		"vind." : "vindication, vindicated",
		"vindic." : "vindication, vindicated",
		"virg." : "virgin(s)",
		"virol." : "virology",
		"viz." : "videlicet, �namely�",
		"voc." : "vocabulary",
		"vocab." : "vocabulary",
		"vol." : "volume",
		"vols." : "volumes",
		"voy." : "voyage(s)",
		"v.r." : "variant reading",
		"v.rr." : "variant readings",
		"vulg." : "vulgar(ly)",
		"vulg." : "vulgar",
		"vulg." : "Vulgate",
		"w." : "west",
		"w." : "west, western",
		"w. afr." : "West Africa(n)",
		"warwicksh." : "Warwickshire",
		"wd." : "word",
		"wd." : "word",
		"west." : "western",
		"westm." : "Westminster",
		"westmld." : "Westmoreland",
		"westmorld." : "Westmoreland",
		"westmrld." : "Westmoreland",
		"will." : "William",
		"wilts." : "Wiltshire",
		"wiltsh." : "Wiltshire",
		"w. ind." : "West Indies, West Indian",
		"w. indies" : "West Indies",
		"wis." : "Wisconsin",
		"wisd." : "wisdom",
		"wisd." : "(in the Apocrypha) Wisdom of Solomon",
		"wk." : "weak",
		"wk." : "week",
		"wk." : "work",
		"wkly." : "weekly",
		"wks." : "works",
		"wonderf." : "wonderful",
		"worc." : "Worcestershire",
		"worcestersh." : "Worcestershire",
		"worcs." : "Worcestershire",
		"writ." : "writing(s)",
		"w. va." : "West Virginia",
		"yearbk." : "yearbook",
		"yng." : "young",
		"yorks." : "Yorkshire",
		"yorksh." : "Yorkshire",
		"yr." : "year",
		"yrs." : "years",
		"zech." : "(in the Bible) Zechariah",
		"zeitschr." : "Zeitschrift",
		"zeph." : "(in the Bible) Zephaniah",
		"zoogeogr." : "zoogeography",
		"zool." : "zoology, zoological"}