context = {"is" : [['it', 'but', 'the', 'and'], ['during', 'in', 'sometimes', 'usually', 'never']],
	"in" : [['is', 'sometimes', 'usually', 'never', 'it'], []],
	"it" : [['during', 'but', 'and'], ['is', 'sometimes', 'usually', 'never', 'in']],
	"during" : [['is', 'never', 'sometimes', 'usually'], ['it', 'but', 'and']],
	"the" : [['is', 'fruit', 'favorite', 'but', 'liked'], ['is', 'but', 'united', 'states']],
	"but" : [['during', 'is', 'the', 'fruit'], ['is', 'it', 'the']],
	"and" : [['during'], ['is', 'it', 'sometimes', 'usually', 'never']],
	"sometimes" : [['is', 'it', 'but', 'and'], ['in', 'during']],
	"usually" : [['is', 'it', 'but', 'and'], ['in', 'during']],
	"never" : [['is', 'it', 'but', 'and'], ['during', 'in']],
	"favorite" : [['least', 'is', 'but', 'his', 'my', 'her', 'your', 'their', 'our'], ['the', 'is', 'fruit', 'but']],
	"least" : [['is', 'but', 'your', 'my', 'her', 'his', 'our', 'their'], ['favorite', 'fruit', 'is', 'liked', 'the', 'but']],
	"fruit" : [['least', 'favorite', 'liked', 'most', 'loved', 'your', 'his', 'our', 'her', 'their', 'my'], ['the', 'is', 'but']],
	"most" : [['is', 'but', 'my', 'your', 'her', 'his'], ['loved', 'is', 'fruit', 'but', 'the']],
	"loved" : [['most', 'is', 'but', 'my', 'her', 'your', 'his', 'our', 'their'], ['the', 'is', 'fruit', 'but']],
	"liked" : [['least', 'is', 'but', 'your', 'my', 'our', 'her', 'his', 'their'], ['the', 'fruit', 'is', 'but']],
	"new" : [[], ['jersey', 'is', 'usually', 'sometimes', 'never']],
	"paris" : [[], ['is', 'never', 'sometimes', 'usually', 'during']],
	"india" : [[], ['is', 'sometimes', 'usually', 'never', 'during']],
	"united" : [['the'], ['states', 'is', 'never', 'sometimes', 'usually']],
	"states" : [['the', 'united'], ['is', 'never', 'during', 'sometimes', 'usually']],
	"california" : [[], ['is', 'during', 'usually', 'never', 'sometimes']],
	"jersey" : [['new'], ['is', 'usually', 'sometimes', 'never', 'during']],
	"france" : [[], ['is', 'sometimes', 'usually', 'never', 'during']],
	"china" : [[], ['is', 'never', 'during', 'sometimes', 'usually']],
	"he" : [[], ['dislikes', 'likes']],
	"she" : [[], ['dislikes', 'likes']],
	"grapefruit" : [['the', 'is', 'fruit', 'and'], ['and', 'is', 'least']],
	"your" : [['the', 'is', 'but'], ['favorite', 'least', 'fruit', 'is', 'most', 'loved', 'liked']],
	"my" : [['the', 'is', 'but'], ['favorite', 'least', 'fruit', 'is', 'most', 'loved', 'liked']],
	"his" : [['the', 'is', 'but'], ['favorite', 'least', 'fruit', 'is', 'most', 'loved', 'liked']],
	"her" : [['the', 'is', 'but'], ['favorite', 'least', 'fruit', 'is', 'most', 'loved', 'liked']],
	"fall" : [['during', 'in', 'is', 'sometimes', 'never', 'usually'], ['it', 'is', 'but', 'and']],
	"june" : [['during', 'in', 'usually', 'never', 'sometimes', 'is'], ['it', 'is', 'and', 'but']],
	"spring" : [['during', 'in', 'sometimes', 'usually', 'is', 'never'], ['it', 'is', 'and', 'but']],
	"january" : [['in', 'during', 'sometimes', 'usually', 'never', 'is'], ['it', 'is', 'and', 'but']],
	"winter" : [['during', 'in', 'usually', 'sometimes', 'never', 'is'], ['it', 'is', 'but', 'and']],
	"march" : [['during', 'in', 'never', 'sometimes', 'is', 'usually'], ['it', 'is', 'and', 'but']],
	"autumn" : [['during', 'in', 'usually', 'sometimes', 'never', 'is'], ['it', 'is', 'but', 'and']],
	"may" : [['in', 'during', 'sometimes', 'never', 'is', 'usually'], ['it', 'is', 'and', 'but']],
	"nice" : [['is', 'it', 'sometimes', 'usually', 'never'], ['during', 'in', 'but', 'and']],
	"september" : [['in', 'during', 'sometimes', 'usually', 'never', 'is'], ['it', 'is', 'and', 'but']],
	"july" : [['in', 'during', 'is', 'usually', 'never', 'sometimes'], ['it', 'is', 'but', 'and']],
	"april" : [['in', 'during', 'sometimes', 'usually', 'never', 'is'], ['it', 'is', 'but', 'and']],
	"november" : [['in', 'during', 'is', 'sometimes', 'usually', 'never'], ['it', 'is', 'and', 'but']],
	"summer" : [['in', 'during', 'never', 'sometimes', 'usually', 'is'], ['it', 'is', 'but', 'and']],
	"december" : [['in', 'during', 'sometimes', 'never', 'usually', 'is'], ['it', 'is', 'but', 'and']],
	"february" : [['during', 'in', 'never', 'usually', 'sometimes', 'is'], ['it', 'is', 'and', 'but']],
	"our" : [['the', 'is', 'but'], ['fruit', 'least', 'favorite', 'is', 'liked', 'most', 'loved']],
	"their" : [['the', 'is', 'but'], ['fruit', 'favorite', 'least', 'is', 'liked', 'most', 'loved']],
	"freezing" : [['is', 'it', 'never', 'usually', 'sometimes'], ['in', 'during', 'but', 'and']],
	"pleasant" : [['is', 'it', 'sometimes', 'never', 'usually'], ['during', 'in', 'but', 'and']],
	"beautiful" : [['is', 'it', 'usually', 'sometimes', 'never'], ['in', 'during', 'and', 'but']],
	"october" : [['in', 'during', 'usually', 'is', 'sometimes', 'never'], ['it', 'is', 'but', 'and']],
	"snowy" : [['is', 'it', 'never', 'sometimes', 'usually'], ['during', 'in', 'and', 'but']],
	"warm" : [['is', 'it', 'sometimes', 'usually', 'never'], ['in', 'during', 'but', 'and']],
	"cold" : [['is', 'it', 'usually', 'sometimes', 'never'], ['in', 'during', 'but', 'and']],
	"wonderful" : [['is', 'it', 'never', 'sometimes', 'usually'], ['during', 'in', 'but', 'and']],
	"dry" : [['is', 'it', 'sometimes', 'never', 'usually'], ['during', 'in', 'but', 'and']],
	"busy" : [['is', 'it', 'sometimes', 'usually', 'never'], ['during', 'in', 'and', 'but']],
	"august" : [['in', 'during', 'never', 'usually', 'sometimes', 'is'], ['it', 'is', 'but', 'and']],
	"chilly" : [['is', 'it', 'never', 'sometimes', 'usually'], ['during', 'in', 'but', 'and']],
	"rainy" : [['is', 'it', 'sometimes', 'usually', 'never'], ['in', 'during', 'and', 'but']],
	"mild" : [['is', 'it', 'sometimes', 'never', 'usually'], ['in', 'during', 'but', 'and']],
	"wet" : [['is', 'it', 'never', 'usually', 'sometimes'], ['during', 'in', 'but', 'and']],
	"relaxing" : [['is', 'it', 'usually', 'never', 'sometimes'], ['in', 'during', 'and', 'but']],
	"quiet" : [['is', 'it', 'usually', 'never', 'sometimes'], ['in', 'during', 'and', 'but']],
	"hot" : [['is', 'it', 'sometimes', 'usually', 'never'], ['in', 'during', 'but', 'and']],
	"dislikes" : [['he', 'she'], ['and', 'grapefruit', 'limes', 'lemons', 'grapes', 'apples', 'peaches', 'mangoes', 'strawberries', 'oranges', 'pears', 'bananas']],
	"likes" : [['he', 'she'], ['and', 'strawberries', 'oranges', 'mangoes', 'apples', 'lemons', 'pears', 'peaches', 'limes', 'grapefruit', 'bananas', 'grapes']],
	"limes" : [['and', 'dislikes', 'likes', 'he', 'she'], ['and']],
	"lemons" : [['and', 'dislikes', 'likes', 'he', 'she'], ['and']],
	"grapes" : [['and', 'dislikes', 'likes', 'he', 'she'], ['and']],
	"mangoes" : [['and', 'dislikes', 'likes', 'he', 'she'], ['and']],
	"apples" : [['and', 'dislikes', 'likes', 'he', 'she'], ['and']],
	"peaches" : [['and', 'dislikes', 'likes', 'he', 'she'], ['and']],
	"oranges" : [['and', 'likes', 'dislikes', 'he', 'she'], ['and']],
	"pears" : [['and', 'likes', 'dislikes', 'she', 'he'], ['and']],
	"strawberries" : [['and', 'likes', 'dislikes', 'he', 'she'], ['and']],
	"bananas" : [['and', 'likes', 'dislikes', 'she', 'he'], ['and']],
	"to" : [['go', 'she', 'he', 'to', 'they'], ['next', 'visit', 'to', 'the', 'go']],
	"grape" : [['the', 'fruit', 'is', 'but'], ['is', 'least', 'but', 'favorite', 'most']],
	"apple" : [['the', 'is', 'fruit', 'but'], ['is', 'least', 'but', 'favorite', 'most']],
	"orange" : [['the', 'fruit', 'is', 'but'], ['is', 'least', 'but', 'favorite', 'most']],
	"lemon" : [['the', 'fruit', 'is', 'but'], ['is', 'least', 'but', 'most', 'favorite']],
	"lime" : [['the', 'fruit', 'is', 'but'], ['is', 'least', 'but', 'favorite', 'most']],
	"banana" : [['the', 'fruit', 'is', 'but'], ['is', 'least', 'but', 'most', 'favorite']],
	"mango" : [['the', 'fruit', 'is', 'but'], ['is', 'least', 'but', 'favorite', 'most']],
	"pear" : [['the', 'is', 'fruit', 'but'], ['is', 'least', 'but', 'most', 'favorite']],
	"strawberry" : [['the', 'fruit', 'is', 'but'], ['is', 'least', 'but', 'most', 'favorite']],
	"peach" : [['the', 'fruit', 'is', 'but'], ['is', 'least', 'but', 'most', 'favorite']],
	"like" : [['they', 'you', 'we', 'i'], ['and', 'oranges', 'mangoes', 'pears', 'apples', 'peaches', 'grapes', 'lemons', 'limes', 'grapefruit', 'strawberries', 'bananas']],
	"dislike" : [['they', 'i', 'you', 'we'], ['and', 'grapes', 'mangoes', 'strawberries', 'peaches', 'apples', 'grapefruit', 'bananas', 'lemons', 'oranges', 'limes', 'pears']],
	"they" : [[], ['like', 'dislike', 'to']],
	"that" : [['she', 'he', 'driving', 'is', 'was'], ['truck', 'car', 'automobile']],
	"i" : [[], ['like', 'dislike']],
	"we" : [[], ['like', 'dislike', 'oranges', 'mangoes', 'peaches', 'pears', 'strawberries', 'bananas', 'grapefruit', 'limes', 'lemons', 'grapes', 'apples']],
	"you" : [[], ['like', 'dislike', 'grapes', 'peaches', 'limes', 'bananas', 'pears', 'grapefruit', 'lemons', 'apples', 'mangoes', 'oranges', 'strawberries']],
	"animal" : [['most', 'favorite', 'my', 'loved', 'your', 'feared', 'her', 'his', 'least'], ['is', 'was', 'that', 'the', 'this']],
	"a" : [['he', 'she', 'driving'], ['truck', 'car', 'automobile', 'old', 'yellow', 'rusty', 'new', 'blue', 'big', 'green', 'little', 'white', 'black', 'shiny', 'red']],
	"truck" : [['a', 'that', 'the', 'old', 'yellow', 'little', 'red', 'new', 'rusty', 'blue', 'green', 'big', 'white', 'shiny', 'black'], []],
	"car" : [['a', 'the', 'that', 'rusty', 'yellow', 'new', 'blue', 'little', 'white', 'old', 'black', 'big', 'red', 'shiny', 'green'], []],
	"automobile" : [['the', 'a', 'that', 'old', 'red', 'big', 'green', 'blue', 'rusty', 'white', 'black', 'new', 'yellow', 'shiny', 'little'], []],
	"was" : [['animal', 'he', 'she', 'most', 'favorite'], ['driving', 'the', 'that', 'most', 'favorite']],
	"next" : [['to', 'visit', 'go', 'going'], []],
	"go" : [['to', 'she', 'he', 'they', 'might', 'wanted', 'wants'], ['to', 'next', 'the', 'last']],
	"driving" : [['she', 'is', 'he', 'was'], ['the', 'a', 'that', 'old', 'yellow', 'little', 'white', 'black', 'rusty', 'blue', 'big', 'green', 'shiny', 'new', 'red']],
	"visit" : [['to', 'plan', 'plans', 'i', 'we', 'they', 'he', 'she'], ['next', 'in']],
	"little" : [['she', 'he', 'that', 'the', 'a', 'driving'], ['truck', 'car', 'automobile', 'red', 'yellow', 'white', 'blue', 'green', 'black']],
	"big" : [['he', 'she', 'a', 'that', 'the', 'driving'], ['automobile', 'truck', 'car', 'green', 'blue', 'white', 'red', 'black', 'yellow']],
	"old" : [['he', 'she', 'a', 'the', 'that', 'driving'], ['truck', 'automobile', 'car', 'yellow', 'red', 'black', 'blue', 'white', 'green']],
	"yellow" : [['a', 'the', 'that', 'driving', 'old', 'rusty', 'little', 'new', 'big', 'shiny'], ['truck', 'car', 'automobile']],
	"red" : [['that', 'the', 'a', 'driving', 'little', 'old', 'new', 'big', 'shiny', 'rusty'], ['truck', 'automobile', 'car']],
	"rusty" : [['she', 'he', 'a', 'the', 'that', 'driving'], ['car', 'truck', 'automobile', 'yellow', 'blue', 'white', 'black', 'green', 'red']],
	"blue" : [['a', 'the', 'that', 'driving', 'new', 'rusty', 'big', 'little', 'shiny', 'old'], ['car', 'truck', 'automobile']],
	"white" : [['the', 'that', 'a', 'driving', 'little', 'rusty', 'new', 'big', 'old', 'shiny'], ['car', 'truck', 'automobile']],
	"black" : [['the', 'that', 'a', 'driving', 'old', 'rusty', 'shiny', 'little', 'big', 'new'], ['car', 'automobile', 'truck']],
	"green" : [['a', 'the', 'that', 'driving', 'big', 'new', 'little', 'shiny', 'rusty', 'old'], ['automobile', 'truck', 'car']],
	"shiny" : [['she', 'he', 'that', 'a', 'the', 'driving'], ['truck', 'automobile', 'car', 'blue', 'red', 'black', 'green', 'yellow', 'white']],
	"are" : [['animals'], ['favorite', 'going', 'to', 'least', 'most']],
	"last" : [['to', 'went', 'go'], []],
	"feared" : [['most', 'your', 'his', 'her', 'my', 'is', 'was'], ['animal', 'animals', 'is', 'was']],
	"animals" : [['most', 'favorite', 'his', 'feared', 'your', 'loved', 'least', 'her', 'my'], ['are', 'were']],
	"this" : [['animal', 'favorite', 'was', 'is'], ['was', 'is']],
	"plan" : [['i', 'we', 'they'], ['to', 'visit']],
	"going" : [['is', 'are', 'she', 'they', 'he', 'why', 'when'], ['to', 'next', 'the']],
	"saw" : [['he', 'she'], ['a', 'that', 'the', 'old', 'yellow', 'new', 'rusty', 'white', 'green', 'blue', 'big', 'shiny', 'black', 'red', 'little']],
	"disliked" : [['she', 'he'], ['a', 'the', 'that', 'rusty', 'yellow', 'little', 'blue', 'big', 'red', 'old', 'shiny', 'white', 'new', 'black', 'green']],
	"drives" : [['he', 'she'], ['a', 'that', 'the', 'new', 'blue', 'little', 'red', 'big', 'rusty', 'white', 'yellow', 'shiny', 'green', 'old', 'black']],
	"drove" : [['she', 'he'], ['a', 'that', 'the', 'big', 'white', 'little', 'green', 'old', 'blue', 'red', 'new', 'black', 'rusty', 'yellow', 'shiny']],
	"between" : [['translating', 'to', 'translate', 'think', 'thinks'], ['and', 'spanish', 'portuguese', 'english', 'french', 'chinese']],
	"translate" : [['to', 'is', "it's", 'difficult', 'easy', 'fun'], ['between', 'and', 'to', 'spanish', 'chinese', 'portuguese', 'english', 'french']],
	"plans" : [['he', 'she'], ['to', 'visit']],
	"were" : [['animals', 'favorite', 'most'], ['most', 'favorite']],
	"went" : [['he', 'they', 'she'], ['to', 'last']],
	"might" : [['she', 'they', 'he'], ['go', 'to']],
	"wanted" : [['she', 'he', 'they'], ['to', 'go']],
	"thinks" : [['he', 'she'], ['translating', 'between', "it's", 'to', 'it', 'is', 'difficult', 'easy', 'fun']],
	"spanish" : [['between', 'to', 'translate', 'and', 'translating'], ['is', 'and', 'to']],
	"portuguese" : [['between', 'translate', 'to', 'and', 'translating'], ['is', 'and', 'to']],
	"chinese" : [['between', 'translate', 'to', 'and', 'translating'], ['is', 'and', 'to']],
	"english" : [['between', 'to', 'translate', 'and', 'translating'], ['is', 'and', 'to']],
	"french" : [['between', 'translate', 'to', 'and', 'translating'], ['is', 'and', 'to']],
	"translating" : [['think', 'thinks', 'i', 'do', 'you', 'he', 'she'], ['between', 'and', 'spanish', 'english', 'portuguese', 'french', 'chinese']],
	"difficult" : [['is', 'and', 'it', "it's", 'thinks', 'think'], ['to', 'translate', 'between']],
	"fun" : [['is', 'and', 'thinks', 'it', "it's", 'think'], ['to', 'translate', 'between']],
	"easy" : [['is', 'and', 'thinks', "it's", 'it', 'think'], ['to', 'translate', 'between']],
	"wants" : [['she', 'he'], ['to', 'go']],
	"think" : [['i', 'do', 'you'], ['translating', 'between', 'it', 'is', "it's", 'to', 'difficult', 'easy', 'fun']],
	"why" : [[], ['going', 'go', "didn't", 'did', 'they', 'we', 'you', 'she', 'he']],
	"it's" : [['thinks', 'i', 'think', 'he', 'she'], ['to', 'translate', 'difficult', 'easy', 'fun']],
	"did" : [['why', 'when'], ['to', 'go', 'she', 'he', 'like', 'they', 'you']],
	"cat" : [['animal', 'that', 'this', 'the', 'was', 'is'], ['was', 'most', 'is']],
	"shark" : [['animal', 'that', 'this', 'the', 'is', 'was'], ['was', 'is', 'most']],
	"bird" : [['animal', 'that', 'the', 'this', 'was', 'is'], ['is', 'most', 'was']],
	"mouse" : [['animal', 'the', 'this', 'that', 'is', 'was'], ['was', 'most', 'is']],
	"horse" : [['animal', 'that', 'this', 'the', 'is', 'was'], ['is', 'most', 'was']],
	"elephant" : [['animal', 'the', 'that', 'this', 'was', 'is'], ['is', 'most', 'was']],
	"dog" : [['animal', 'the', 'that', 'this', 'is', 'was'], ['is', 'was', 'most']],
	"monkey" : [['animal', 'the', 'this', 'that', 'is', 'was'], ['is', 'most', 'was']],
	"lion" : [['animal', 'this', 'that', 'the', 'was', 'is'], ['was', 'is', 'most']],
	"bear" : [['animal', 'this', 'the', 'that', 'is', 'was'], ['was', 'most', 'is']],
	"rabbit" : [['animal', 'that', 'the', 'this', 'was', 'is'], ['was', 'most', 'is']],
	"snake" : [['animal', 'this', 'that', 'the', 'was', 'is'], ['was', 'most', 'is']],
	"when" : [[], ['going', 'is', 'did', 'she', 'go', 'are', 'he', 'we', 'they']],
	"want" : [['they'], ['to', 'go']],
	"do" : [[], ['you', 'think', 'translating', 'like']],
	"how" : [[], ['was', 'your', 'visit', 'the', 'weather']],
	"elephants" : [['animals', 'favorite', 'were', 'are'], ['were', 'most', 'are']],
	"horses" : [['animals', 'are', 'favorite', 'were'], ['are', 'most', 'were']],
	"dogs" : [['animals', 'were', 'are', 'favorite'], ['are', 'were', 'most']],
	"sharks" : [['animals', 'are', 'were', 'favorite'], ['were', 'most', 'are']],
	"snakes" : [['animals', 'are', 'were', 'favorite'], ['were', 'most', 'are']],
	"cats" : [['animals', 'were', 'are', 'favorite'], ['were', 'most', 'are']],
	"rabbits" : [['animals', 'favorite', 'were', 'are'], ['were', 'most', 'are']],
	"monkeys" : [['animals', 'favorite', 'are', 'were'], ['are', 'most', 'were']],
	"bears" : [['animals', 'were', 'favorite', 'are'], ['are', 'most', 'were']],
	"birds" : [['animals', 'favorite', 'were', 'are'], ['are', 'most', 'were']],
	"lions" : [['animals', 'were', 'favorite', 'are'], ['are', 'were', 'most']],
	"mice" : [['animals', 'are', 'favorite', 'were'], ['were', 'most', 'are']],
	"didn't" : [['why'], ['go', 'to', 'they', 'we', 'she', 'he', 'you']],
	"eiffel" : [['the', 'to', 'going', 'go'], ['tower']],
	"tower" : [['the', 'eiffel', 'to'], []],
	"grocery" : [['the', 'to', 'going', 'go'], ['store']],
	"store" : [['the', 'grocery', 'to'], []],
	"football" : [['the', 'to', 'going', 'go'], ['field']],
	"field" : [['the', 'football', 'to'], []],
	"lake" : [['the', 'to', 'going', 'go'], []],
	"school" : [['the', 'to', 'going', 'go'], []],
	"would" : [[], ['like', 'to', 'you', 'they', 'he', 'she']],
	"aren't" : [['why'], ['going', 'to', 'you', 'they', 'we']],
	"been" : [['has', 'she', 'he', 'have', 'you'], ['to', 'the']],
	"weather" : [['how', 'was', 'the'], ['in', 'last', 'india', 'the', 'united', 'california', 'france']],
	"does" : [[], ['like', 'she', 'the', 'he']],
	"has" : [[], ['been', 'to', 'she', 'he']],
	"isn't" : [['why'], ['going', 'to', 'she', 'he']],
	"am" : [['when'], ['i', 'going', 'to']],
	"where" : [[], ['is', 'the']],
	"have" : [[], ['you', 'been', 'to']],
	}